/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Lobo
 */
public class Vista_profe extends javax.swing.JFrame {

    /**
     * Creates new form Vista_profe
     */
    public Vista_profe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_vista_profe01 = new javax.swing.JButton();
        Button_vista_profe02 = new javax.swing.JButton();
        Button_vista_profe03 = new javax.swing.JButton();
        profe_LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_vista_profe01.setText("Ver lista por asignatura");
        Button_vista_profe01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_vista_profe01MouseClicked(evt);
            }
        });

        Button_vista_profe02.setText("       Ver profesores      ");
        Button_vista_profe02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_vista_profe02MouseClicked(evt);
            }
        });

        Button_vista_profe03.setText("      Agregar notas        ");
        Button_vista_profe03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_vista_profe03MouseClicked(evt);
            }
        });

        profe_LogOut.setText("Cerrar Sesion");
        profe_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profe_LogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_vista_profe01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_vista_profe02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_vista_profe03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profe_LogOut))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(profe_LogOut)
                .addGap(29, 29, 29)
                .addComponent(Button_vista_profe01)
                .addGap(43, 43, 43)
                .addComponent(Button_vista_profe02)
                .addGap(44, 44, 44)
                .addComponent(Button_vista_profe03)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_vista_profe01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_vista_profe01MouseClicked
        Vista_profe_lista vista_profe_lista = new Vista_profe_lista();
        vista_profe_lista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_vista_profe01MouseClicked

    private void Button_vista_profe02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_vista_profe02MouseClicked
        Vista_profe_profe vista_profe_profe = new Vista_profe_profe();
        vista_profe_profe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_vista_profe02MouseClicked

    private void Button_vista_profe03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_vista_profe03MouseClicked
        Vista_profe_agregar vista_profe_agregar = new Vista_profe_agregar();
        vista_profe_agregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Button_vista_profe03MouseClicked

    private void profe_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profe_LogOutMouseClicked
        Select_user select_user = new Select_user();
        select_user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profe_LogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_profe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_profe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_profe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_profe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_profe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_vista_profe01;
    private javax.swing.JButton Button_vista_profe02;
    private javax.swing.JButton Button_vista_profe03;
    private javax.swing.JButton profe_LogOut;
    // End of variables declaration//GEN-END:variables
}
